on:
  push:
    branches:
      - master
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          OUT_DIR: docs
          # Provide personal access token
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
